name: coverage
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: npm ci

      - name: Check Coverage
        run: npm run coverage


